[package]
name = "game"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
getrandom = { version = "0.3", default-features = false, features = ["wasm_js"] }
serde_json = "1.0.145"
serde = { version = "1.0.228", features = ["derive"] }